### ISSUE TITLE
Empty Array as Output

### ISSUE THREAD

**Issue by Michaelvons** [words/powerthesaurus-api#4]
When I try the sample code, no data is outputted. What setup step am I missing?

I have done the obvious `npm install` but when I try a sample e.g "shoe" I no an empty array.

Please help.

**Comment by wooorm** [comment]
This project seems to be broken, because PowerThesaurus keeps changing their website: https://github.com/words/powerthesaurus-api/issues/3

**Comment by zeke** [comment]
Bummer :[

Sorry about that!

**Comment by rockroland** [comment]
confirmed that there are no results when tested with runkit

**Comment by zeke** [comment]
Yep. It's busted.

I would suggest reaching out to the PowerThesaurus folks to see if they have plans to support an API: https://www.powerthesaurus.org/_feedback

**Comment by zeke** [comment]
This should be fixed, y'all. Give it a try: https://github.com/words/powerthesaurus-api/pull/5#issuecomment-690532508
